### ISSUE TITLE
Changing workflow name doesn't update scheduled builds

### ISSUE THREAD

**Issue by wattson12** [bitrise-io/bitrise.io#25]
I had a workflow which had a name change (as a result of spaces in names causing builds to fail), but the scheduled build failed with the same errors as before the name change 

I also couldn't see a way to edit the scheduled build (not sure if this is a bug of a feature request since I know its still in beta)

**Comment by viktorbenei** [comment]
Hi,

Changing the workflow name does not have any effect on Scheduled builds - in fact it doesn't have any effect outside of the configuration (bitrise.yml) itself. This is by design (we tried to minimise the connection of the configuration to any other resource), but feel free to create a UserVoice feature request.

Re: scheduled builds - you're right, right now there's no "edit" option. Please go ahead and create a UserVoice feature request, I believe this should be handled properly.
The solution right now is to add a new Schedule, and delete/remove the previous one.
