### ISSUE TITLE
Android API Appcompat v7-23.2.0 causes build fail 

### ISSUE THREAD

**Issue by kshitizshakya** [bitrise-io/bitrise.io#32]
Appcompat v4 - 23.2.0 fails the build for android.

We have appcompat v7-23.1.1 and 
build on compileSdkVersion 23  
buildToolsVersion '23.0.2'

**Comment by viktorbenei** [comment]
Hi,

We'll soon pre-install this package.
Right now you'll have to install it yourself. It's quite easy, you can find a guide on our DevCenter: http://devcenter.bitrise.io/docs/how-to-install-an-additional-android-sdk-version

You just have to determine what's the package's ID you want to install (run `android list sdk --no-ui --all --extended` on your Mac/Linux, as noted in the guide), add a Script step to your Workflow on bitrise.io, and install the package(s) you want to with a one-liner:

`echo y | android update sdk --no-ui --all --filter package-1,package-2` (where `package-1` and `package-2` are the package IDs you want to install).

You can do this for a single package, or for as many as you want to - just separate them with a comma, without a space.

**Comment by gaurav-fueled** [comment]
We would need to run this script ```echo y | android update sdk --no-ui --all --filter extra-android-support,extra-android-m2repository```

**Comment by viktorbenei** [comment]
Just a bit of info why it takes so long to refresh the Android VM/docker image on Bitrise.io :

We use Docker Hub's automated builds feature to create new docker images every time the code changes on GitHub. 

This approach has many advantages, including that it verifies that's the image was actually built from the source on GitHub, as automated build images reject every other source (you can't just manually release an image if it's an automated build image). 

Now, the issue is that Docker Hub no longer can build the Android NDK image. We suspect this is related to it's size. We tried it quite a few times with no success so far. 

Right now we're testing alternatives, e.g. to build the image on Bitrise.io. The issue is, you can't turn an automated build docker image to a non automated one on Docker Hub, so we might have to register it as a new image. 

We're still searching for a better solution and experimenting with different solutions/workarounds, that's why the delay in Android image updates. We'll make this happen sooner or later, we just need a bit more time 😉

**Comment by guitcastro** [comment]
AS a quick workaround you can use the [Update SDK Step](https://github.com/guitcastro/steps-update-sdk) and  add `extra-android-m2repository` as System Images parameters (this is odd) but it will work.

**Comment by viktorbenei** [comment]
The latest AppCompat version is now pre-installed, you can read more about the new update schedule on our Blog: http://blog.bitrise.io/2016/03/14/virtual-machine-and-weekly-cache-updates.html
