### ISSUE TITLE
Building Multi-Platform Repository

### ISSUE THREAD

**Issue by toshi0383** [bitrise-io/bitrise.io#42]
Hi, is it possible to host a multi platform repository ?
I tried to "ADD NEW APP" from web, but couldn't proceed from "Validation".
Could I maybe skip the validation step ?

For example I have a repository like this.
I'd like to manually build and test the app using command-line tools including Gradle, ndk-build, and xcodebuild.

```
Library Foo/
- Foo/  # written in C
    - core/
    etc...
- Foo_iOS/  # written in C, C++, and Objective-C
    - core/
        - core_iOS.xcodeproj
        - core_tvOS.xcodeproj
        etc...
    - sampleApp/
        - sampleApp.xcodeproj
        etc...
- Foo_Android/ # written in C, C++, and Java
    - core/
        - app/build.gradle
        - settings.gradle
        etc...
    - wrapperLibrary/
        - app/build.gradle
        - settings.gradle
        etc...
    - sampleApp/
        - app/build.gradle
        - settings.gradle
        etc...
```

**Comment by viktorbenei** [comment]
> .. is it possible to host a multi platform repository .. Could I maybe skip the validation step ?

Yes you can - https://bitrise-io.github.io/devcenter/adding-a-new-app/setting-up-configuration/#skipping-the-scanner-full-manual-configuration

**But** most of the stacks are not designed to build both Android and iOS in a single build. This is because if you build native iOS and Android projects you'll almost always have significantly different configs for the two build project. The suggested method right now is to register the repo as two separate apps, one for iOS and one for Android.

The only stacks which have both iOS and Android tools pre-installed are the Xamarin stacks, but those are updated based on Xamarin update cycles, and not based on Android or Xcode update/tool cycles.

> I'd like to manually build and test the app using command-line tools including Gradle, ndk-build, and xcodebuild.

Using Gradle is not a hard task, but using `xcodebuild` from scripts can be, if you want to do anything more than just running tests. E.g. to generate an IPA you have to:

1. install the required code signing files (Certificate installer step)
2. Archive the project with `xcodebuild`
3. Export the IPA from the generated archive

The last two are handled in the Xcode Archive step. You can check the step's code, it's not super hard but not trivial either.

I'll close this issue, but if you need more info feel free to ask!
