### ISSUE TITLE
Android SDK on OSX?

### ISSUE THREAD

**Issue by Almouro** [bitrise-io/bitrise.io#45]
Hi guys!

At @bamlab, we use Bitrise for our React Native projects, and we like to build both Android and iOS versions of the project on the same stack. 
For now, we made a custom step installing Android SDK with Brew via a script, and adding the required tools.

Do you think it would be a good idea to include the Android SDK on the OSX stacks? If so, should we make a PR on https://github.com/bitrise-io/osx-box-bootstrap?
Or do you think it'd be best to submit an Android SDK step for the OS stacks?

Thanks! :)

**Comment by viktorbenei** [comment]
Hi,

We definitely have plans for cross platform stacks, but there are a couple of things we have to consider:

1. How should we schedule updates for the stack? Should it be updated to the latest Xcode version automatically? To the latest React Native / Cordova / node / etc.?
2. It's not possible to run macOS **inside** a Docker container. Docker can run on a macOS host, but the guest can only be Linux. The issue is, there's no real alternative for macOS right now, to provide images for the environment. We try to move in the direction that you can download & use the same environment you have on Bitrise, for easier configuration & debugging. That's possible with Docker and with a Linux guest (when your build "runs on Linux"), and we plan to support this use case (to let you work with the same environment on your Mac/PC) even more in the future, as that makes development and testing way easier. Unfortunately we don't know about any possible solution for macOS, and because of licensing issues we can't even provide the virtual machine images we use on bitrise.io. This means that all we can provide are the scripts we use to prepare the clean macOS (https://github.com/bitrise-io/osx-box-bootstrap), but you have to create the virtual machine yourself and then run the scripts on it. This is quite a complicated process, usually too complicated to be a viable debug option.

There are other pros & cons, like if you have your app configured as two projects/apps on Bitrise (one for macOS/iOS and one for Linux/Android), then you can run the two builds in parallel (given that you have at least 2 concurrency on bitrise.io), as well as other, usually less significant points like to be able to have control over the tool versions separately for your two configuration (e.g. a newer Node version for one config, an older one for the other one).

So, right now we can't promise anything. We definitely aware of this use case and we're thinking about the best solution, but we have to consider quite a lot of things.

Feel free to vote & comment here, we're eager to hear what you think! Every use case you share can help us refine the requirements, and to get us closer to the "right" solution 😉

**Comment by viktorbenei** [comment]
This issue was moved to https://discuss.bitrise.io/t/android-sdk-on-osx/152
