### ISSUE TITLE
Github connectivity issue

### ISSUE THREAD

**Issue by dumoko** [bitrise-io/bitrise.io#57]
Hi!

> Cloning into '/var/folders/lb/8n5bn9k975qgw662jpqdy7mm0000gn/T/d20160808-943-crpdg0'...
fatal: unable to access 'https://github.com/Augustyniak/RATreeView.git/': Failed to connect to github.com port 443: Operation timed out

Seems that smth went wrong on the connectivity level. It actually caused an important build to fail...
Mb it's possible to check it out, so in the future this issue is going to be less likely to occur again.

Thanks for your great effort!

**Comment by viktorbenei** [comment]
Unfortunately connectivity issues are always a possibility in a cloud environment - we do our best to make sure the issue is not on our part, but it's certainly possible that it was an intermittent issue on GitHub's side.

Did it work after a rebuild/retry?

In general, the best you can do is to retry the failed network operation with a short delay, these connectivity issues are usually temporary and a retry should work.

Thanks for reporting the issue, and let us know if there's anything we can do, or if the issue would happen again.
