### ISSUE TITLE
[unconfirmed] 'Code signing & Files' in Workflow Editor is picking up older provisioning profile 

### ISSUE THREAD

**Issue by shamikagasc** [bitrise-io/bitrise.io#98]
Steps:
1. Navigate to workflow Editor
2. Uploaded a wildcard provisioning profile for testing builds
3. Deleted all provisioning profiles & uploaded a new provisioning profile
4. Kick off a new build

Build log shows that the older profile is still being downloaded & used

**Comment by viktorbenei** [comment]
Closing this issue - the reason of the issue was that the user did overwrite the `BITRISE_PROVISION_URL` env var through Build Trigger env var params. When you overwrite this env var (`BITRISE_PROVISION_URL`), no prov profile from bitrise.io will be downloaded, because the URL of those would be passed through this env var to the build.
